SET FOREIGN_KEY_CHECKS = 0 ^;
TRUNCATE `sys_role` ^;
SET FOREIGN_KEY_CHECKS = 1 ^;

SET SQL_SAFE_UPDATES = 0 ^;
DELETE FROM `sys_role` ^;
SET SQL_SAFE_UPDATES = 1 ^;

INSERT IGNORE INTO `sys_role`(`roleName`) VALUES('ROLE_USER') ^;
INSERT IGNORE INTO `sys_role`(`roleName`) VALUES('ROLE_ADMIN') ^;